# Generated by Django 5.1.4 on 2025-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('PollingUnit_uniqueid', models.IntegerField()),
            ],
            options={
                'db_table': 'agentname',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedStateResults',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('party_abreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_state_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedWardResults',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=50)),
                ('party_abreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_ward_results',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partyid', models.CharField(max_length=11)),
                ('partyname', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(max_length=11)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='pollingunit',
            old_name='state_id',
            new_name='polling_unit_id',
        ),
        migrations.RemoveField(
            model_name='announcedlgaresults',
            name='id',
        ),
        migrations.RemoveField(
            model_name='announcedlgaresults',
            name='lga_id',
        ),
        migrations.RemoveField(
            model_name='announcedlgaresults',
            name='party_abbreviation',
        ),
        migrations.RemoveField(
            model_name='announcedpuresults',
            name='id',
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='entered_by_user',
            field=models.CharField(default='Unkown', max_length=50),
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='lga_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='party_abreviation',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='result_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedlgaresults',
            name='user_ip_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedpuresults',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcedpuresults',
            name='entered_by_user',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedpuresults',
            name='result_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcedpuresults',
            name='user_ip_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lga',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lga',
            name='entered_by_user',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lga',
            name='lga_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lga',
            name='state_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lga',
            name='uniqueid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lga',
            name='user_ip_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='lat',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='long',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='user_ip_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='entered_by_user',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='lga_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='uniqueid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='user_ip_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='party_abbreviation',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='polling_unit_uniqueid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniqueid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='announcedlgaresults',
            table='announced_lga_results',
        ),
        migrations.AlterModelTable(
            name='announcedpuresults',
            table='announced_pu_results',
        ),
        migrations.AlterModelTable(
            name='lga',
            table='lga',
        ),
        migrations.AlterModelTable(
            name='pollingunit',
            table='polling_unit',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='ward',
        ),
    ]
