# Generated by Django 5.1.4 on 2025-01-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_agentname_announcedstateresults_announcedwardresults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingunit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='states',
            name='id',
        ),
        migrations.AlterField(
            model_name='agentname',
            name='name_id',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcedlgaresults',
            name='entered_by_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniqueid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='state_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='states',
            table='states',
        ),
    ]
