# Generated by Django 5.1.4 on 2025-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_pollingunit_id_remove_states_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='name_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
