# Generated by Django 5.1.4 on 2025-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_agentname_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcedlgaresults',
            old_name='party_abreviation',
            new_name='party_abbreviation',
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
